config/routes.rb
Rails.application.routes.draw do
  get "gossips/show"
  get "welcome/user"
  get "static_pages/home"
  get "static_pages/team"
  get "static_pages/contact"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Route de la page d'accueil
  root 'static_pages#home'

  # Vérification de la santé de l'application (utile pour les tests)
  get "up" => "rails/health#show", as: :rails_health_check


  # Routes pour les pages statiques
  get '/static_pages/team', to:'static_pages#team'
  get '/static_pages/contact', to:'static_pages#contact'

  # Route avec nom d'utilisateur dynamique
  get '/welcome/:user_name', to: 'welcome#user'

  get '/gossips/:id', to: 'gossips#show'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
    has_many :users
end

app/models/gossip.rb
class Gossip < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    belongs_to :city
    has_many :gossips
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  def show
    @gossip = Gossip.find(params[:id]) 
  

  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @list_goss = Gossip.all
    @gossip = Gossip.find_by(params[:id])
  end

  def team
    
  end

  def contact
    
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def user
    @user_name = params[:user_name]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/gossips/show.html.erb
<h1>Fiche Profil</h1>

<p>Email de l'auteur : <%= @gossip.user.email %></p>

<p>Âge de l'auteur : <%= @gossip.user.age %></p>

<p>Description de l'auteur : <%= @gossip.user.description %></p>

<p>Le gossip : <%= @gossip.content %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <title><%= content_for(:title) || "The Gossip Project" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.2/css/bootstrap.min.css" rel="stylesheet">
    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>


  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Team", static_pages_team_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Contact", static_pages_contact_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Welcome", welcome_user_path, class: "nav-link" %>
          </li>
        </ul>
      </div>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/static_pages/contact.html.erb
<h1>Contact</h1>
<p>Num de la team :</p>
<p>1111-4444-2222</p>

app/views/static_pages/home.html.erb
<html>
  <head>
    <title>The Gossip Project</title>
  </head>

  <body>
    <h1>Bienvenu sur mon super site de gossip!</h1>
    <br>

    <p>
    <% @list_goss.each do |list| %>
      <strong><%= link_to "Auteur :", gossips_show_path(list.id) %></strong> <%= list.user.first_name %> <%= list.user.last_name %><br>
      
      <strong>Titre :</strong> <%= list.title %><br>
      <br>
    <% end %>
    
    
    </p>
  <body>
</html>

app/views/static_pages/team.html.erb
<h1>Team</h1>

<img src="https://openup.fr/wp-content/uploads/2022/08/How-to-motivate-teambuilding1-1024x576.png.webp" class="img-fluid" alt="team">

<p><strong>La team :</strong></p>
<p>James BARTHEE</p>

app/views/welcome/user.html.erb
<h1>Bienvenue, <%= @user_name %> !</h1>
<p>Nous sommes ravis de te voir ici sur The Gossip Project.</p>